--- Dockerfile
+++ Dockerfile
@@ -2,7 +2,7 @@
 FROM gcr.io/oss-fuzz-base/base-builder
 RUN apt-get update && apt-get install -y ffmpeg python3-pip gtk-doc-tools libffi-dev
-RUN pip3 install meson==0.55.3 ninja
+RUN pip3 install meson ninja
 
 RUN git clone --depth 1 https://gitlab.gnome.org/GNOME/gdk-pixbuf.git
 
 
